### ISSUE TITLE
Ensure quotes containing \ are properly rendered.

### ISSUE THREAD

**Issue by hackerpants** [akerl/madlibrarian-lambda#1]
One of the quotes is supposed to contain the shrug emoji but it looks like the \ is missing

Test case::
 ¯\\_(ツ)_/¯

:)

**Comment by hackerpants** [comment]
semi serious issue, since you could just use \\ 

thats an escaped backslash.. since the same thing is happening in the comments box here... as you might expect ...

**Comment by akerl** [comment]
Hah! The bug wasn't unicode at all. It's that in YAML, `"¯\_(ツ)_/¯"` reads the backslash as an escaping of the next character, which is why the backslash *and* the underscore vanish. Switching to `"¯\\_(ツ)_/¯"` fixes it
